language: node_js
node_js:
- lts/*
cache:
  directories:
  - node_modules
before_install:
- npm install -g typescript
before_script:
- npm install
- npm run setup
- npm run build:client
- npm run build:server
deploy:
  provider: heroku
  api_key:
    secure: UEUKebkmv2xMdP4Wbk5mm07JOXqyGrP4XE18cqqdfTiH31gvUnC9m6VwiLgUIIsD4yQNeTwjz88H8xcbVN09Lxbvs1L34FlwWtiHrUFLczO2Xl4nG7vKExr7EF3wVD1TDiFoiv0qUc3lEP+jMf3AmtRImtZNaccqN1Mhhbf0zrl3Jr7kXYZvggzlRxy+WXZPQaqTwEFcf8TrQCSsd+e97TlI2kQv24ABekP6lyblmN2pi0rmHLKvbovOP9nRNW/qU+27mDwGQ3M6Y+QdtTQv3frqCKnMjqfDhuj8wsifo3CUU8h0FyOy6Bteuwz0Auf/oEsZMWiw6k8VQeG7lScP41wxuIL2Ypxd816R/4SrZPhyoBDXC4LmmlbZdM8lbxRNaXVQtVjM56pDqlb649AG8Cs2Oj2qXX2cMVEi/s4M0cadQIdWtRU7ZDB3bj1NdcGjOAy7mLRmY8cx1wsPumdg46yXY9zaro5d3S6TKHKH0zbGE3yxPw2hNzVR1A95NRFWFhXLft9P+8jY8MrBPVYdMjepehmJzNPbjWPUvnXV9gKJNLYEFuZx3DDFoA78UR04KZ2ceEgnBuMUA9IqqZCtG6fm3O7PBze58LrqBIhjpSkqzBlu3dYQiX4xjvTtiywAdgYomgdh3uLGT0yGtgL2WAJjjAyr9j1IgqfK9hBIOZo=
  app: photoboard
  on:
    repo: lfaudreejr/PhotoBoard
env:
  global:
    secure: OsOCkTqmwM8hJ3EuVREvXpfJN5FEL0hinXlCCuCicTJGUb5WcXR7FptcGo33W0lcsd9TSIdUBQ3ZQ+Mqq1vtOAJSJIrCe45GxitA430mHrDlc3QcGYx7ewIbj2I6O0Sbl2uqDmkGI7xsudkmD49w2S0QDZklIFw4KtPLrQzFLgos9p0rSkA5xWz+0HAHLZGUTfiFlyDa6HT5wB5gVzfgVA1MorKc2VWE9ypd4zZkk1ekZa6aWUFf5hkKlGEYskysdulI8sAoVUFZsNI30pAlxi//HtgzaMamXhQO12zphMvcekMM3AyCNDV8XeBFmGE4wVRruOGJiDwZEaW5NLKP3K1SNHpz75TE51zbpM9gzqWv0C7gcdIJFfGAUxlw0Ovz1yl0p6XtSxRXuUvnIIBYqzQZYe/VYB7dtzXWqv0qHqa95BI0t9BLYyN5wJrsqhArKJyrqPPQl/QicMm5KXEg7ZQ3EF1dUnvL3qF9V2sShZb9xp1/+TIaUNdsGBJbVOvfCMaWY0lea/R6J+sfirEHZC3RRwbAM3al15mFn8ZACS0it44AaNKq8WFoC8XsG8MzdxpqggHRX/QwO7jlYCr0zJx3I3ChGQA+lq0b0cmmPmEVudehgBlspFRsacuip64H7+Nh499Z0fybkMWRdT5VzNW3LaPanOTntKyO9XCfljs=
