language: node_js
node_js:
- iojs
- '8'
cache:
  directories:
  - node_modules
before_deploy:
  - sh scripts/remove-ignore.sh
deploy:
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: Rn2/APlJwkdyouuEQbLDtFpSWgjCRTIq/cA993G2kQEZ9uzi7r2Gn+Erb8oel7kpcE8aJHGbB46ukSqSDBITEu/UydSfRGCXMQM07TQgFVFO0hX8EKCrf1R2FB/Qh823TwICVEmrGiiFpCX7wZTD9/PqI82b3p25l4ZKbH++z/SqI/rX7s0Iobeh6FUFoAVu7ryMixnlr+7B2Klf1SR2zEi5KXtVpyl+Mxk+ESJXAcypvD2m1oxXXAfi/Df/dZuxyORQufZS4HHJW09dGlLB5ML70/dU0whWk8f4umjbt7CGfmYs7HH9RGdLasPYrvvFXE2+4Znj1RLWNlYy3fP4P9IQMwn2YeNeM+X23Pv9jdZ63HbHFnFuHHbgyNjg+4nfa+tB+6u/bjqVK2NYDnHcwfYpcK28NJPgL8K/+BtPA6/N4uHUMvGTIWuFPiOdD+7xcb2d1EPmKTIUxL4/Z9OgQx3BPaXnH4LA4Zm0zqB3ke1lpZa97e5xMSjrKIuciDGuheRSOLLvQNwMgMLVTEDwgkoqtIfCivAR0q7RgoV/jq9sDKCAzeVt5KJzkLVTvL9+kfr47kvjExsqhY0S3Rws+IOO58xZCPE7jVSCHehY2qTkwdH+cq+feYzM/m9hlyDgziMOJUrcCrynjWur2OVK5swQ6PTIxW3UNLUTxgX0OvY=
  app: PictureBoard
  on:
    repo: lfaudreejr/PictureBoard
