language: node_js
node_js:
- lts/*
cache:
  directories:
  - node_modules
before_install:
- npm install -g typescript
before_script:
- npm install
- npm run setup
- npm run build:client
- npm run build:server
deploy:
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: Mrk8dpg8PfMdZ+wsGsZS9H1MtvlZTsmXgIL+W060Bl2OPaQGKgkrPXrWTDn88gFeQloIstWX1GjlbqIASH3giFg/ZF9BKAIUiNmz9UupH90NUNWSzVPSDMFthL5jjZ7WWotn2WyPcwhDMilLCzKW7DiX0Ymt/gVYfPF5AiUiwOaPtMNAQy7tp9r3mgZLlIFFYGkOSKTzKNwo4idiGKwMcKdgI0TrP7P3e3o57oxwqGgH3/rGRA6Qm9y5UCLzPdk/Dc5n2bpJgiteMJRHyOoR8hSd/WughRBo7kDnwy9EuXUQ6136/cjVSApRwoOMrKZhKPc2Z8r2KO3mBUuXJ8hc6P+IlIrNn71gZ5RSOxEBCK6M7JNF8MrIq7SkgBObf2njPVWiLqG0UTwiSCZIP0d8T7JX1yf3rERHZ7sQQqpIKfUHCw7xR9rP1+ObXsRXdOYc1YLQnTNyipv10fDbMSkQa0a+GV/sdCEIzG6nTtSdoEsXfruaNEiEOdHu6pW4lMDqpb4YDox21cE47TBQMdTqZkNkYm7HkakPFA6DUWaNwV+MLDMlhsmI8S6tIk3teClLeUCMBm6SpA0gCbTnf15L2YSlJF89n+0FJPP0UCVCVo7KLY+sK1Lisf51JVIDGb4f2VQE1zwgadofpgiitboKZpxxAcsk4UGPLZCIv05d4rA=
  app: photoboard
  on:
    repo: lfaudreejr/PhotoBoard
env:
  global:
    secure: OsOCkTqmwM8hJ3EuVREvXpfJN5FEL0hinXlCCuCicTJGUb5WcXR7FptcGo33W0lcsd9TSIdUBQ3ZQ+Mqq1vtOAJSJIrCe45GxitA430mHrDlc3QcGYx7ewIbj2I6O0Sbl2uqDmkGI7xsudkmD49w2S0QDZklIFw4KtPLrQzFLgos9p0rSkA5xWz+0HAHLZGUTfiFlyDa6HT5wB5gVzfgVA1MorKc2VWE9ypd4zZkk1ekZa6aWUFf5hkKlGEYskysdulI8sAoVUFZsNI30pAlxi//HtgzaMamXhQO12zphMvcekMM3AyCNDV8XeBFmGE4wVRruOGJiDwZEaW5NLKP3K1SNHpz75TE51zbpM9gzqWv0C7gcdIJFfGAUxlw0Ovz1yl0p6XtSxRXuUvnIIBYqzQZYe/VYB7dtzXWqv0qHqa95BI0t9BLYyN5wJrsqhArKJyrqPPQl/QicMm5KXEg7ZQ3EF1dUnvL3qF9V2sShZb9xp1/+TIaUNdsGBJbVOvfCMaWY0lea/R6J+sfirEHZC3RRwbAM3al15mFn8ZACS0it44AaNKq8WFoC8XsG8MzdxpqggHRX/QwO7jlYCr0zJx3I3ChGQA+lq0b0cmmPmEVudehgBlspFRsacuip64H7+Nh499Z0fybkMWRdT5VzNW3LaPanOTntKyO9XCfljs=
