language: node_js
node_js:
- iojs
- '8'
cache:
  directories:
  - node_modules
before_install:
- openssl aes-256-cbc -K $encrypted_8ccd6defe5da_key -iv $encrypted_8ccd6defe5da_iv
  -in index.js.enc -out ./client/src/config/index.js -d
deploy:
  provider: heroku
  api_key:
    secure: mxgIFPLxzCWl4nr2Vb8s8M7bw6YSc8Zz770RVwxIPYaKplHvgPbdCv7f5Y3VVvbvcK0L4WkwzzlvyVqZG3VvohL+kQYbIrwHY9wVif5vghJG8rML//mxQ2P39VyhabwgwXWNe/BE0PnjhgGbAzi153lcB1ePvcA9J1glEwI352yvvMA66QagmlT38NALkE5usgxyFuVPXyYLeUQpCPF6DTywpSJEtxPNFPahjF9AMDEB+gtXLFeDJ/xCiuNRN85qb5nGkXkz7pzP2nDOu12aG24K/VnoNNPNR74PgHRWAvVWngvj5xu+WAW2xgdykZBt2BFmlCD2OMPVH41+hJzp2JqFY8bSDwXN8zCthsQ1kH4AhOI/3zbAta6K8k9dYG+tOKG77lII7TxatllQ0CfBiK+DA8gS8w5DXbdlFJzvl6dcRXxT65BJNVhuXe8NF0ewZHjgFY2v3CUMZ3WKKZ0WttqaTJGouT4dnDbTvFrSvNBSHjcYL17Kd1LLs/BlZvV/jq/NPmV1yzLwVQdXo1utxeh52PhMMJ3jmQ7vUvLKrsVmeR4F4BqFVAkdWb1q+GIGv47x2y7TkJxaB6iHXO4NuZ1pODITkZv/s0OUWB7v4wbK0d2OKlUoR/0J8J6cLyTxK6fYnr5Nw9MTCV6MFQQ81T6G1QMyUFAIJULfoj3kbpk=
  app: photoboard
  on:
    repo: lfaudreejr/PhotoBoard
