"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const user_router_1 = require("../users/user-router");
const boards_router_1 = require("../boards/boards-router");
const pins_router_1 = require("../pins/pins-router");
const router = express_1.Router();
router.use('/user', user_router_1.default);
router.use('/boards', boards_router_1.default);
router.use('/pins', pins_router_1.default);
exports.default = router;
